/**
 * Boot the game and write catalog files to src/model/catalogs/.
 * Re-run after upgrading kittensgame-master/.
 *
 * inScope semantics: an entry is `inScope: true` iff
 *   (a) its `prices` field contains no `paragon` or `karma` entry, AND
 *   (b) its subsystem isn't categorically reset-gated.
 *
 * Categorically-OOS subsystems: prestigePerks (paragon), transcendenceUpgrades
 * (require transcendenceTier > 0 which is reset-only), voidUpgrades (require
 * void resource which is post-reset). Cryptotheology is a single gateway tech,
 * not a separate metadata array — the tech itself is in-scope; what it unlocks
 * is in transcendenceUpgrades.
 *
 * If you add a new catalog whose entries are reset-gated by mechanism (not by
 * direct paragon/karma cost), set its category-flag to false in the call below.
 */
import { setupGame } from "@/testdriver/setupGame";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const OUT_DIR = resolve("src/model/catalogs");
mkdirSync(OUT_DIR, { recursive: true });

const h = setupGame();
const g = h.gamePage;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function hasParagonOrKarma(entry: any): boolean {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
  const prices: unknown = entry?.prices ?? entry?.cost ?? [];
  if (!Array.isArray(prices)) return false;
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-explicit-any
  return prices.some((p: any) => p?.name === "paragon" || p?.name === "karma");
}

interface PriceEntry {
  name: string;
  val: number;
}
interface CatEntry {
  name: string;
  inScope: boolean;
  basePrices: PriceEntry[];
  priceRatio: number;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function entries(arr: any, categoryInScope = true): CatEntry[] {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-return
  return (arr ?? [])
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .filter((x: any) => typeof x?.name === "string")
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .map((x: any) => {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      const raw: PriceEntry[] = (x.prices ?? x.cost ?? []) as PriceEntry[];
      const basePrices = Array.isArray(raw)
        ? raw.map((p) => ({ name: String(p.name), val: Number(p.val) }))
        : [];
      const priceRatio = typeof x.priceRatio === "number" ? (x.priceRatio as number) : 1;
      return {
        name: x.name as string,
        inScope: categoryInScope && !hasParagonOrKarma(x),
        basePrices,
        priceRatio,
      };
    });
}

function metaLine(d: CatEntry): string {
  const prices = d.basePrices
    .map((p) => `{ name: ${JSON.stringify(p.name)}, val: ${p.val} }`)
    .join(", ");
  return `  ${JSON.stringify(d.name)}: { inScope: ${d.inScope}, basePrices: [${prices}], priceRatio: ${d.priceRatio} },`;
}

function emitCatalog(
  fileName: string,
  constName: string,
  typeName: string,
  data: CatEntry[],
): void {
  if (data.length === 0) {
    const content = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const ${constName}_NAMES = [] as const;

export type ${typeName} = never;

export interface ${typeName}Meta {
  inScope: boolean;
  basePrices: { name: string; val: number }[];
  priceRatio: number;
}

export const ${constName}_META: Record<string, ${typeName}Meta> = {};
`;
    writeFileSync(resolve(OUT_DIR, fileName), content);
    return;
  }
  const namesArr = data.map((d) => `"${d.name}"`).join(",\n  ");
  const metaEntries = data.map(metaLine).join("\n");
  const content = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const ${constName}_NAMES = [
  ${namesArr},
] as const;

export type ${typeName} = (typeof ${constName}_NAMES)[number];

export interface ${typeName}Meta {
  inScope: boolean;
  basePrices: { name: string; val: number }[];
  priceRatio: number;
}

export const ${constName}_META: Record<${typeName}, ${typeName}Meta> = {
${metaEntries}
};
`;
  writeFileSync(resolve(OUT_DIR, fileName), content);
}

// Subsystems entirely out of scope (paragon/karma reachability).
const OOS_PRESTIGE = false;
const OOS_TRANSCENDENCE = false;
const OOS_CRYPTOTHEOLOGY = false;
const OOS_VOIDUPGRADES = false; // requires void resource → reset

// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
emitCatalog("resources.ts", "RESOURCE", "ResourceName", entries(g.resPool.resources));
emitCatalog(
  "buildings.ts",
  "BUILDING",
  "BuildingName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.bld.buildingsData ?? g.bld.meta?.[0]?.meta),
);
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
emitCatalog("techs.ts", "TECH", "TechName", entries(g.science.techs));
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
emitCatalog("workshop.ts", "WORKSHOP", "WorkshopName", entries(g.workshop.upgrades));
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
emitCatalog("crafts.ts", "CRAFT", "CraftName", entries(g.workshop.crafts));
emitCatalog(
  "religionUpgrades.ts",
  "RELIGION_UPGRADE",
  "ReligionUpgradeName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.religion.religionUpgrades),
);
emitCatalog(
  "zigguratUpgrades.ts",
  "ZIGGURAT",
  "ZigguratName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.religion.zigguratUpgrades),
);
emitCatalog(
  "transcendenceUpgrades.ts",
  "TRANSCENDENCE",
  "TranscendenceName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.religion.transcendenceUpgrades, OOS_TRANSCENDENCE),
);
emitCatalog(
  "cryptotheology.ts",
  "CRYPTOTHEOLOGY",
  "CryptotheologyName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.religion.cryptotheologyUpgrades, OOS_CRYPTOTHEOLOGY),
);
emitCatalog(
  "chronoforge.ts",
  "CHRONOFORGE",
  "ChronoforgeName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.time.chronoforgeUpgrades),
);
emitCatalog(
  "voidspace.ts",
  "VOIDSPACE",
  "VoidspaceName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.time.voidspaceUpgrades),
);
emitCatalog(
  "voidUpgrades.ts",
  "VOID_UPGRADE",
  "VoidUpgradeName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.void?.voidUpgrades, OOS_VOIDUPGRADES),
);
emitCatalog(
  "spacePrograms.ts",
  "SPACE_PROGRAM",
  "SpaceProgramName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.space.programs),
);
emitCatalog(
  "policies.ts",
  "POLICY",
  "PolicyName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.science.policies),
);
emitCatalog(
  "prestigePerks.ts",
  "PRESTIGE_PERK",
  "PrestigePerkName",
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  entries(g.prestige?.perks, OOS_PRESTIGE),
);

// Jobs and races: simple name lists, always in-scope.
function emitNameList(fileName: string, constName: string, typeName: string, names: string[]): void {
  const arr = names.map((n) => `"${n}"`).join(",\n  ");
  const content = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const ${constName}_NAMES = [
  ${arr},
] as const;

export type ${typeName} = (typeof ${constName}_NAMES)[number];
`;
  writeFileSync(resolve(OUT_DIR, fileName), content);
}

// eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-explicit-any
const jobs: string[] = (g.village.jobs ?? g.village.sim?.jobs ?? []).map((j: any) => j.name as string);
emitNameList("jobs.ts", "JOB", "JobName", jobs);

// eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-explicit-any
const races: string[] = (g.diplomacy.races ?? []).map((r: any) => r.name as string);
emitNameList("civs.ts", "CIV", "CivName", races);

// Planets — special: per-planet building dictionary.
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
const planets = g.space.planets ?? [];
// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
const planetNames: string[] = planets.map((p: any) => p.name as string);
const planetBuildingMeta: Record<string, CatEntry[]> = {};
for (const p of planets) {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
  planetBuildingMeta[p.name as string] = entries(p.buildings);
}

const planetsContent = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const PLANET_NAMES = [
  ${planetNames.map((n) => `"${n}"`).join(",\n  ")},
] as const;

export type PlanetName = (typeof PLANET_NAMES)[number];

export interface PlanetBuildingMeta {
  inScope: boolean;
  basePrices: { name: string; val: number }[];
  priceRatio: number;
}

export const PLANET_BUILDING_META: Record<PlanetName, Record<string, PlanetBuildingMeta>> = {
${Object.entries(planetBuildingMeta)
  .map(([planet, builds]) => {
    const lines = builds
      .map((b) => {
        const prices = b.basePrices
          .map((p) => `{ name: ${JSON.stringify(p.name)}, val: ${p.val} }`)
          .join(", ");
        return `    ${JSON.stringify(b.name)}: { inScope: ${b.inScope}, basePrices: [${prices}], priceRatio: ${b.priceRatio} },`;
      })
      .join("\n");
    return `  ${JSON.stringify(planet)}: {\n${lines}\n  },`;
  })
  .join("\n")}
};

export const PLANET_BUILDING_NAMES: Record<PlanetName, readonly string[]> = {
${Object.entries(planetBuildingMeta)
  .map(
    ([planet, builds]) =>
      `  ${JSON.stringify(planet)}: [${builds.map((b) => `"${b.name}"`).join(", ")}] as const,`,
  )
  .join("\n")}
};
`;
writeFileSync(resolve(OUT_DIR, "planets.ts"), planetsContent);

// Per-civ pact tier max — populated where pacts exist.
// In Kittens Game, leviathans support the Mausoleum unicorn-relic pacts (no tiers in
// the current base game; pacts are applied as boolean activations). For now we set
// PACT_TIERS_MAX to 0 for everyone except known tiered pact races.
// Inspect g.religion.pacts at runtime if present.
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
const pactsArr = g.religion?.pactsManager?.pacts ?? g.religion?.pacts ?? [];
const pactCount = Array.isArray(pactsArr) ? pactsArr.length : 0;

const pactTiersMax: Record<string, number> = {};
for (const r of races) pactTiersMax[r] = 0;
// Leviathans: mausoleum pacts. Set tier max from pactCount if any exist; default 0
// otherwise. Refine as the model gets clearer.
if (pactCount > 0) pactTiersMax["leviathans"] = 0; // placeholder; current base has no tiers

function pactLines(rs: string[]): string {
  return rs.map((r) => `  ${JSON.stringify(r)}: ${pactTiersMax[r] ?? 0},`).join("\n");
}

const civsExtraContent = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

import type { CivName } from "./civs";

export const PACT_TIERS_MAX: Record<CivName, number> = {
${pactLines(races)}
};
`;

writeFileSync(resolve(OUT_DIR, "pacts.ts"), civsExtraContent);

// Index file re-exports.
const indexContent = `// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export * from "./resources";
export * from "./buildings";
export * from "./techs";
export * from "./workshop";
export * from "./crafts";
export * from "./religionUpgrades";
export * from "./zigguratUpgrades";
export * from "./transcendenceUpgrades";
export * from "./cryptotheology";
export * from "./chronoforge";
export * from "./voidspace";
export * from "./voidUpgrades";
export * from "./spacePrograms";
export * from "./policies";
export * from "./prestigePerks";
export * from "./jobs";
export * from "./civs";
export * from "./planets";
export * from "./pacts";
`;
writeFileSync(resolve(OUT_DIR, "index.ts"), indexContent);

// eslint-disable-next-line no-console
console.log(
  `wrote: resources(${"x"}), buildings, techs, workshop, crafts, religion, ziggurat, transcendence, cryptotheology, chronoforge, voidspace, void, space, policies, prestige, jobs(${jobs.length}), civs(${races.length}), planets(${planetNames.length}), pacts`,
);
await h.teardown();
