// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const CHRONOFORGE_NAMES = [
  "temporalBattery",
  "blastFurnace",
  "timeBoiler",
  "controlledDelay",
  "temporalAccelerator",
  "temporalImpedance",
  "ressourceRetrieval",
  "temporalPress",
] as const;

export type ChronoforgeName = (typeof CHRONOFORGE_NAMES)[number];

export interface ChronoforgeNameMeta {
  inScope: boolean;
}

export const CHRONOFORGE_META: Record<ChronoforgeName, ChronoforgeNameMeta> = {
  "temporalBattery": { inScope: true },
  "blastFurnace": { inScope: true },
  "timeBoiler": { inScope: true },
  "controlledDelay": { inScope: true },
  "temporalAccelerator": { inScope: true },
  "temporalImpedance": { inScope: true },
  "ressourceRetrieval": { inScope: true },
  "temporalPress": { inScope: true },
};
