// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const CIV_NAMES = [
  "lizards",
  "sharks",
  "griffins",
  "nagas",
  "zebras",
  "spiders",
  "dragons",
  "leviathans",
] as const;

export type CivName = (typeof CIV_NAMES)[number];
