// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const CRAFT_NAMES = [
  "wood",
  "beam",
  "slab",
  "plate",
  "steel",
  "concrate",
  "gear",
  "alloy",
  "eludium",
  "scaffold",
  "ship",
  "tanker",
  "kerosene",
  "parchment",
  "manuscript",
  "compedium",
  "blueprint",
  "thorium",
  "megalith",
  "bloodstone",
  "tMythril",
] as const;

export type CraftName = (typeof CRAFT_NAMES)[number];

export interface CraftNameMeta {
  inScope: boolean;
}

export const CRAFT_META: Record<CraftName, CraftNameMeta> = {
  "wood": { inScope: true },
  "beam": { inScope: true },
  "slab": { inScope: true },
  "plate": { inScope: true },
  "steel": { inScope: true },
  "concrate": { inScope: true },
  "gear": { inScope: true },
  "alloy": { inScope: true },
  "eludium": { inScope: true },
  "scaffold": { inScope: true },
  "ship": { inScope: true },
  "tanker": { inScope: true },
  "kerosene": { inScope: true },
  "parchment": { inScope: true },
  "manuscript": { inScope: true },
  "compedium": { inScope: true },
  "blueprint": { inScope: true },
  "thorium": { inScope: true },
  "megalith": { inScope: true },
  "bloodstone": { inScope: true },
  "tMythril": { inScope: true },
};
