// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const CRYPTOTHEOLOGY_NAMES = [] as const;

export type CryptotheologyName = never;

export interface CryptotheologyNameMeta {
  inScope: boolean;
}

export const CRYPTOTHEOLOGY_META: Record<string, CryptotheologyNameMeta> = {};
