// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const CRYPTOTHEOLOGY_NAMES = [] as const;

export type CryptotheologyName = never;

export interface CryptotheologyNameMeta {
  inScope: boolean;
  basePrices: { name: string; val: number }[];
  priceRatio: number;
}

export const CRYPTOTHEOLOGY_META: Record<string, CryptotheologyNameMeta> = {};
