// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const JOB_NAMES = [
  "woodcutter",
  "farmer",
  "scholar",
  "hunter",
  "miner",
  "priest",
  "geologist",
  "engineer",
] as const;

export type JobName = (typeof JOB_NAMES)[number];
