// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

import type { CivName } from "./civs";

export const PACT_TIERS_MAX: Record<CivName, number> = {
  "lizards": 0,
  "sharks": 0,
  "griffins": 0,
  "nagas": 0,
  "zebras": 0,
  "spiders": 0,
  "dragons": 0,
  "leviathans": 0,
};
