// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const PLANET_NAMES = [
  "cath",
  "moon",
  "dune",
  "piscine",
  "helios",
  "terminus",
  "kairo",
  "yarn",
  "umbra",
  "charon",
  "centaurusSystem",
  "furthestRing",
] as const;

export type PlanetName = (typeof PLANET_NAMES)[number];

export interface PlanetBuildingMeta {
  inScope: boolean;
}

export const PLANET_BUILDING_META: Record<PlanetName, Record<string, PlanetBuildingMeta>> = {
  "cath": {
    "spaceElevator": { inScope: true },
    "sattelite": { inScope: true },
    "spaceStation": { inScope: true },
  },
  "moon": {
    "moonOutpost": { inScope: true },
    "moonBase": { inScope: true },
  },
  "dune": {
    "planetCracker": { inScope: true },
    "hydrofracturer": { inScope: true },
    "spiceRefinery": { inScope: true },
  },
  "piscine": {
    "researchVessel": { inScope: true },
    "orbitalArray": { inScope: true },
  },
  "helios": {
    "sunlifter": { inScope: true },
    "containmentChamber": { inScope: true },
    "heatsink": { inScope: true },
    "sunforge": { inScope: true },
  },
  "terminus": {
    "cryostation": { inScope: true },
  },
  "kairo": {
    "spaceBeacon": { inScope: true },
  },
  "yarn": {
    "terraformingStation": { inScope: true },
    "hydroponics": { inScope: true },
  },
  "umbra": {
    "hrHarvester": { inScope: true },
    "navigationRelay": { inScope: true },
    "spaceShuttle": { inScope: true },
  },
  "charon": {
    "entangler": { inScope: true },
  },
  "centaurusSystem": {
    "tectonic": { inScope: true },
    "moltenCore": { inScope: true },
  },
  "furthestRing": {

  },
};

export const PLANET_BUILDING_NAMES: Record<PlanetName, readonly string[]> = {
  "cath": ["spaceElevator", "sattelite", "spaceStation"] as const,
  "moon": ["moonOutpost", "moonBase"] as const,
  "dune": ["planetCracker", "hydrofracturer", "spiceRefinery"] as const,
  "piscine": ["researchVessel", "orbitalArray"] as const,
  "helios": ["sunlifter", "containmentChamber", "heatsink", "sunforge"] as const,
  "terminus": ["cryostation"] as const,
  "kairo": ["spaceBeacon"] as const,
  "yarn": ["terraformingStation", "hydroponics"] as const,
  "umbra": ["hrHarvester", "navigationRelay", "spaceShuttle"] as const,
  "charon": ["entangler"] as const,
  "centaurusSystem": ["tectonic", "moltenCore"] as const,
  "furthestRing": [] as const,
};
