// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const RELIGION_UPGRADE_NAMES = [
  "solarchant",
  "scholasticism",
  "goldenSpire",
  "sunAltar",
  "stainedGlass",
  "solarRevolution",
  "basilica",
  "templars",
  "apocripha",
  "transcendence",
] as const;

export type ReligionUpgradeName = (typeof RELIGION_UPGRADE_NAMES)[number];

export interface ReligionUpgradeNameMeta {
  inScope: boolean;
}

export const RELIGION_UPGRADE_META: Record<ReligionUpgradeName, ReligionUpgradeNameMeta> = {
  "solarchant": { inScope: true },
  "scholasticism": { inScope: true },
  "goldenSpire": { inScope: true },
  "sunAltar": { inScope: true },
  "stainedGlass": { inScope: true },
  "solarRevolution": { inScope: true },
  "basilica": { inScope: true },
  "templars": { inScope: true },
  "apocripha": { inScope: true },
  "transcendence": { inScope: true },
};
