// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const SPACE_PROGRAM_NAMES = [
  "orbitalLaunch",
  "moonMission",
  "duneMission",
  "piscineMission",
  "heliosMission",
  "terminusMission",
  "kairoMission",
  "rorschachMission",
  "yarnMission",
  "umbraMission",
  "charonMission",
  "centaurusSystemMission",
  "furthestRingMission",
] as const;

export type SpaceProgramName = (typeof SPACE_PROGRAM_NAMES)[number];

export interface SpaceProgramNameMeta {
  inScope: boolean;
}

export const SPACE_PROGRAM_META: Record<SpaceProgramName, SpaceProgramNameMeta> = {
  "orbitalLaunch": { inScope: true },
  "moonMission": { inScope: true },
  "duneMission": { inScope: true },
  "piscineMission": { inScope: true },
  "heliosMission": { inScope: true },
  "terminusMission": { inScope: true },
  "kairoMission": { inScope: true },
  "rorschachMission": { inScope: true },
  "yarnMission": { inScope: true },
  "umbraMission": { inScope: true },
  "charonMission": { inScope: true },
  "centaurusSystemMission": { inScope: true },
  "furthestRingMission": { inScope: true },
};
