// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const TRANSCENDENCE_NAMES = [
  "blackObelisk",
  "blackNexus",
  "blackCore",
  "singularity",
  "blackLibrary",
  "blackRadiance",
  "blazar",
  "darkNova",
  "mausoleum",
  "holyGenocide",
] as const;

export type TranscendenceName = (typeof TRANSCENDENCE_NAMES)[number];

export interface TranscendenceNameMeta {
  inScope: boolean;
  basePrices: { name: string; val: number }[];
  priceRatio: number;
}

export const TRANSCENDENCE_META: Record<TranscendenceName, TranscendenceNameMeta> = {
  "blackObelisk": { inScope: false, basePrices: [{ name: "relic", val: 100 }], priceRatio: 1.15 },
  "blackNexus": { inScope: false, basePrices: [{ name: "relic", val: 5000 }], priceRatio: 1.15 },
  "blackCore": { inScope: false, basePrices: [{ name: "relic", val: 10000 }], priceRatio: 1.15 },
  "singularity": { inScope: false, basePrices: [{ name: "relic", val: 25000 }], priceRatio: 1.15 },
  "blackLibrary": { inScope: false, basePrices: [{ name: "relic", val: 30000 }], priceRatio: 1.15 },
  "blackRadiance": { inScope: false, basePrices: [{ name: "relic", val: 37500 }], priceRatio: 1.15 },
  "blazar": { inScope: false, basePrices: [{ name: "relic", val: 50000 }], priceRatio: 1.15 },
  "darkNova": { inScope: false, basePrices: [{ name: "relic", val: 75000 }, { name: "void", val: 7500 }], priceRatio: 1.15 },
  "mausoleum": { inScope: false, basePrices: [{ name: "relic", val: 50000 }, { name: "void", val: 12500 }, { name: "necrocorn", val: 10 }], priceRatio: 1.15 },
  "holyGenocide": { inScope: false, basePrices: [{ name: "relic", val: 100000 }, { name: "void", val: 25000 }], priceRatio: 1.15 },
};
