// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const TRANSCENDENCE_NAMES = [
  "blackObelisk",
  "blackNexus",
  "blackCore",
  "singularity",
  "blackLibrary",
  "blackRadiance",
  "blazar",
  "darkNova",
  "mausoleum",
  "holyGenocide",
] as const;

export type TranscendenceName = (typeof TRANSCENDENCE_NAMES)[number];

export interface TranscendenceNameMeta {
  inScope: boolean;
}

export const TRANSCENDENCE_META: Record<TranscendenceName, TranscendenceNameMeta> = {
  "blackObelisk": { inScope: false },
  "blackNexus": { inScope: false },
  "blackCore": { inScope: false },
  "singularity": { inScope: false },
  "blackLibrary": { inScope: false },
  "blackRadiance": { inScope: false },
  "blazar": { inScope: false },
  "darkNova": { inScope: false },
  "mausoleum": { inScope: false },
  "holyGenocide": { inScope: false },
};
