// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const VOID_UPGRADE_NAMES = [
  "spaceCathedral",
] as const;

export type VoidUpgradeName = (typeof VOID_UPGRADE_NAMES)[number];

export interface VoidUpgradeNameMeta {
  inScope: boolean;
}

export const VOID_UPGRADE_META: Record<VoidUpgradeName, VoidUpgradeNameMeta> = {
  "spaceCathedral": { inScope: false },
};
