// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const VOIDSPACE_NAMES = [
  "cryochambers",
  "usedCryochambers",
  "voidHoover",
  "voidRift",
  "chronocontrol",
  "voidResonator",
] as const;

export type VoidspaceName = (typeof VOIDSPACE_NAMES)[number];

export interface VoidspaceNameMeta {
  inScope: boolean;
}

export const VOIDSPACE_META: Record<VoidspaceName, VoidspaceNameMeta> = {
  "cryochambers": { inScope: false },
  "usedCryochambers": { inScope: true },
  "voidHoover": { inScope: true },
  "voidRift": { inScope: true },
  "chronocontrol": { inScope: true },
  "voidResonator": { inScope: true },
};
