// AUTO-GENERATED by scripts/generate-catalogs.ts. Do not hand-edit.

export const ZIGGURAT_NAMES = [
  "unicornTomb",
  "ivoryTower",
  "ivoryCitadel",
  "skyPalace",
  "unicornUtopia",
  "sunspire",
  "marker",
  "unicornGraveyard",
  "unicornNecropolis",
  "blackPyramid",
] as const;

export type ZigguratName = (typeof ZIGGURAT_NAMES)[number];

export interface ZigguratNameMeta {
  inScope: boolean;
}

export const ZIGGURAT_META: Record<ZigguratName, ZigguratNameMeta> = {
  "unicornTomb": { inScope: true },
  "ivoryTower": { inScope: true },
  "ivoryCitadel": { inScope: true },
  "skyPalace": { inScope: true },
  "unicornUtopia": { inScope: true },
  "sunspire": { inScope: true },
  "marker": { inScope: true },
  "unicornGraveyard": { inScope: true },
  "unicornNecropolis": { inScope: true },
  "blackPyramid": { inScope: true },
};
